/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TrisPackage;

import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author joels
 */
public class TrisGui extends javax.swing.JFrame {
    private TrisClass trisPvP;
    /**
     * Creates new form TrisGui
     */
    public TrisGui() {
        initComponents();
        trisPvP=new TrisClass();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gamePage = new javax.swing.JPanel();
        buttonBox9 = new javax.swing.JButton();
        buttonBox8 = new javax.swing.JButton();
        buttonBox7 = new javax.swing.JButton();
        buttonBox6 = new javax.swing.JButton();
        buttonBox5 = new javax.swing.JButton();
        buttonBox4 = new javax.swing.JButton();
        buttonBox3 = new javax.swing.JButton();
        buttonBox2 = new javax.swing.JButton();
        buttonBox1 = new javax.swing.JButton();
        gameBackground = new javax.swing.JLabel();
        welcomePage = new javax.swing.JPanel();
        continueButton = new javax.swing.JButton();
        settingsButton = new javax.swing.JButton();
        welcomeBackground = new javax.swing.JLabel();
        modePage = new javax.swing.JPanel();
        chooseMode = new javax.swing.JLabel();
        AIButton = new javax.swing.JButton();
        friendButton = new javax.swing.JButton();
        modeBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(450, 800));
        setMinimumSize(new java.awt.Dimension(450, 800));
        getContentPane().setLayout(null);

        gamePage.setMaximumSize(new java.awt.Dimension(450, 800));
        gamePage.setMinimumSize(new java.awt.Dimension(450, 800));
        gamePage.setPreferredSize(new java.awt.Dimension(450, 800));
        gamePage.setLayout(null);

        buttonBox9.setContentAreaFilled(false);
        buttonBox9.setMaximumSize(new java.awt.Dimension(112, 112));
        buttonBox9.setMinimumSize(new java.awt.Dimension(112, 112));
        buttonBox9.setPreferredSize(new java.awt.Dimension(112, 112));
        buttonBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBox9ActionPerformed(evt);
            }
        });
        gamePage.add(buttonBox9);
        buttonBox9.setBounds(298, 460, 112, 112);

        buttonBox8.setContentAreaFilled(false);
        buttonBox8.setMaximumSize(new java.awt.Dimension(112, 112));
        buttonBox8.setMinimumSize(new java.awt.Dimension(112, 112));
        buttonBox8.setPreferredSize(new java.awt.Dimension(112, 112));
        buttonBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBox8ActionPerformed(evt);
            }
        });
        gamePage.add(buttonBox8);
        buttonBox8.setBounds(170, 460, 112, 112);

        buttonBox7.setContentAreaFilled(false);
        buttonBox7.setMaximumSize(new java.awt.Dimension(112, 112));
        buttonBox7.setMinimumSize(new java.awt.Dimension(112, 112));
        buttonBox7.setPreferredSize(new java.awt.Dimension(112, 112));
        buttonBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBox7ActionPerformed(evt);
            }
        });
        gamePage.add(buttonBox7);
        buttonBox7.setBounds(42, 460, 112, 112);

        buttonBox6.setContentAreaFilled(false);
        buttonBox6.setMaximumSize(new java.awt.Dimension(112, 112));
        buttonBox6.setMinimumSize(new java.awt.Dimension(112, 112));
        buttonBox6.setPreferredSize(new java.awt.Dimension(112, 112));
        buttonBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBox6ActionPerformed(evt);
            }
        });
        gamePage.add(buttonBox6);
        buttonBox6.setBounds(298, 340, 112, 112);

        buttonBox5.setContentAreaFilled(false);
        buttonBox5.setMaximumSize(new java.awt.Dimension(112, 112));
        buttonBox5.setMinimumSize(new java.awt.Dimension(112, 112));
        buttonBox5.setPreferredSize(new java.awt.Dimension(112, 112));
        buttonBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBox5ActionPerformed(evt);
            }
        });
        gamePage.add(buttonBox5);
        buttonBox5.setBounds(170, 340, 112, 112);

        buttonBox4.setContentAreaFilled(false);
        buttonBox4.setMaximumSize(new java.awt.Dimension(112, 112));
        buttonBox4.setMinimumSize(new java.awt.Dimension(112, 112));
        buttonBox4.setPreferredSize(new java.awt.Dimension(112, 112));
        buttonBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBox4ActionPerformed(evt);
            }
        });
        gamePage.add(buttonBox4);
        buttonBox4.setBounds(42, 340, 112, 112);

        buttonBox3.setContentAreaFilled(false);
        buttonBox3.setMaximumSize(new java.awt.Dimension(112, 112));
        buttonBox3.setMinimumSize(new java.awt.Dimension(112, 112));
        buttonBox3.setPreferredSize(new java.awt.Dimension(112, 112));
        buttonBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBox3ActionPerformed(evt);
            }
        });
        gamePage.add(buttonBox3);
        buttonBox3.setBounds(298, 220, 112, 112);

        buttonBox2.setContentAreaFilled(false);
        buttonBox2.setMaximumSize(new java.awt.Dimension(112, 112));
        buttonBox2.setMinimumSize(new java.awt.Dimension(112, 112));
        buttonBox2.setPreferredSize(new java.awt.Dimension(112, 112));
        buttonBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBox2ActionPerformed(evt);
            }
        });
        gamePage.add(buttonBox2);
        buttonBox2.setBounds(170, 220, 112, 112);

        buttonBox1.setContentAreaFilled(false);
        buttonBox1.setMaximumSize(new java.awt.Dimension(112, 112));
        buttonBox1.setMinimumSize(new java.awt.Dimension(112, 112));
        buttonBox1.setPreferredSize(new java.awt.Dimension(112, 112));
        buttonBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBox1ActionPerformed(evt);
            }
        });
        gamePage.add(buttonBox1);
        buttonBox1.setBounds(42, 220, 112, 112);

        gameBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/gameBackground.png"))); // NOI18N
        gamePage.add(gameBackground);
        gameBackground.setBounds(0, 0, 450, 800);

        getContentPane().add(gamePage);
        gamePage.setBounds(0, 0, 450, 800);

        welcomePage.setMaximumSize(new java.awt.Dimension(450, 800));
        welcomePage.setMinimumSize(new java.awt.Dimension(450, 800));
        welcomePage.setPreferredSize(new java.awt.Dimension(450, 800));
        welcomePage.setLayout(null);

        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });
        welcomePage.add(continueButton);
        continueButton.setBounds(162, 580, 90, 30);

        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });
        welcomePage.add(settingsButton);
        settingsButton.setBounds(190, 630, 20, 20);

        welcomeBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/welcomeBackground.png"))); // NOI18N
        welcomePage.add(welcomeBackground);
        welcomeBackground.setBounds(0, 0, 450, 800);

        getContentPane().add(welcomePage);
        welcomePage.setBounds(0, 0, 450, 800);

        modePage.setLayout(null);

        chooseMode.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        chooseMode.setForeground(new java.awt.Color(255, 255, 255));
        chooseMode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chooseMode.setText("Choose your play mode:");
        modePage.add(chooseMode);
        chooseMode.setBounds(110, 480, 240, 30);

        AIButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AIButtonActionPerformed(evt);
            }
        });
        modePage.add(AIButton);
        AIButton.setBounds(190, 540, 72, 20);

        friendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                friendButtonActionPerformed(evt);
            }
        });
        modePage.add(friendButton);
        friendButton.setBounds(190, 590, 72, 20);

        modeBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/modeBackground.png"))); // NOI18N
        modeBackground.setPreferredSize(new java.awt.Dimension(450, 800));
        modePage.add(modeBackground);
        modeBackground.setBounds(0, 0, 450, 800);

        getContentPane().add(modePage);
        modePage.setBounds(0, 0, 450, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void verifica(int row,int col, JButton button){
        int result = trisPvP.Muovi(row, col);
        String type;
        if (result >= 0) {
            if(result > 0){
                type = "O";
            } else {
                type = "X";
            }
            
            button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon" + type)));
            trisPvP.checkWinner();
            } else {
                 JOptionPane.showMessageDialog(this, "Mossa non valida!", "Avviso", JOptionPane.WARNING_MESSAGE);
        }
    }
    private void buttonBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBox1ActionPerformed
        verifica(0,0, buttonBox1);
    }//GEN-LAST:event_buttonBox1ActionPerformed

    private void buttonBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBox2ActionPerformed
        // TODO add your handling code here:
        trisPvP.Muovi(0, 1);
        trisPvP.checkWinner();
    }//GEN-LAST:event_buttonBox2ActionPerformed

    private void buttonBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBox3ActionPerformed
        // TODO add your handling code here:
        trisPvP.Muovi(0, 2);
        trisPvP.checkWinner();
    }//GEN-LAST:event_buttonBox3ActionPerformed

    private void buttonBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBox4ActionPerformed
        // TODO add your handling code here:
        trisPvP.Muovi(1, 0);
        trisPvP.checkWinner();
    }//GEN-LAST:event_buttonBox4ActionPerformed

    private void buttonBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBox5ActionPerformed
        // TODO add your handling code here:
        trisPvP.Muovi(1, 1);
        trisPvP.checkWinner();
    }//GEN-LAST:event_buttonBox5ActionPerformed

    private void buttonBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBox6ActionPerformed
        // TODO add your handling code here:
        trisPvP.Muovi(1, 2);
        trisPvP.checkWinner();
    }//GEN-LAST:event_buttonBox6ActionPerformed

    private void buttonBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBox7ActionPerformed
        // TODO add your handling code here:
        trisPvP.Muovi(2, 0);
        trisPvP.checkWinner();
    }//GEN-LAST:event_buttonBox7ActionPerformed

    private void buttonBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBox8ActionPerformed
        // TODO add your handling code here:
        trisPvP.Muovi(2, 1);
        trisPvP.checkWinner();
    }//GEN-LAST:event_buttonBox8ActionPerformed

    private void buttonBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBox9ActionPerformed
        // TODO add your handling code here:
        trisPvP.Muovi(2, 2);
        trisPvP.checkWinner();
    }//GEN-LAST:event_buttonBox9ActionPerformed

    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_continueButtonActionPerformed

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_settingsButtonActionPerformed

    private void AIButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AIButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AIButtonActionPerformed

    private void friendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_friendButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_friendButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrisGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrisGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrisGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrisGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrisGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AIButton;
    private javax.swing.JButton buttonBox1;
    private javax.swing.JButton buttonBox2;
    private javax.swing.JButton buttonBox3;
    private javax.swing.JButton buttonBox4;
    private javax.swing.JButton buttonBox5;
    private javax.swing.JButton buttonBox6;
    private javax.swing.JButton buttonBox7;
    private javax.swing.JButton buttonBox8;
    private javax.swing.JButton buttonBox9;
    private javax.swing.JLabel chooseMode;
    private javax.swing.JButton continueButton;
    private javax.swing.JButton friendButton;
    private javax.swing.JLabel gameBackground;
    private javax.swing.JPanel gamePage;
    private javax.swing.JLabel modeBackground;
    private javax.swing.JPanel modePage;
    private javax.swing.JButton settingsButton;
    private javax.swing.JLabel welcomeBackground;
    private javax.swing.JPanel welcomePage;
    // End of variables declaration//GEN-END:variables
}
